name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . -f dockerfile --tag mahmom/jenkins_sprints:${{ github.sha }}
    - name: push the Docker image
      run: docker push mahmom/jenkins_sprints:${{ github.sha }}     
