name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: docker login -u ${{ secrets.DOCKERHUBUSER }} -p ${{ secrets.DOCKERHUBPASS }}
    - name: Build the Docker image
      run: docker build . -f dockerfile --tag omarquraah/jenkins_sprints:v3
    - name: push the Docker image
      run: docker push omarquraah/jenkins_sprints:${{ github.sha }}     
